export enum RoomActionTypes {
    GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST',
    GET_ROOMS_RESULT = 'GET_ROOMS_RESULT',
    GET_ROOM_REQUEST = 'GET_ROOM_REQUEST',
    GET_ROOM_RESULT = 'GET_ROOM_RESULT',
    ADD_ROOM_REQUEST = 'ADD_ROOM_REQUEST',
    ADD_ROOM_RESULT = 'ADD_ROOM_RESULT',
    EDIT_ROOM_REQUEST = 'EDIT_ROOM_REQUEST',
    EDIT_ROOM_RESULT = 'EDIT_ROOM_RESULT',
    DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST',
    DELETE_ROOM_RESULT = 'DELETE_ROOM_RESULT',
}

export enum UserActionTypes {
    GET_USERS_REQUEST = 'GET_USERS_REQUEST',
    GET_USERS_RESULT = 'GET_USERS_RESULT',
    GET_USER_REQUEST = 'GET_USER_REQUEST',
    GET_USER_RESULT = 'GET_USER_RESULT',
}

export enum ItemActionTypes {
    GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST',
    GET_ITEMS_RESULT = 'GET_ITEMS_RESULT',
    GET_ITEM_REQUEST = 'GET_ITEM_REQUEST',
    GET_ITEM_RESULT = 'GET_ITEM_RESULT',
}

export enum LoginActionTypes {
    REGISTER_REQUEST = 'REGISTER_REQUEST',
    REGISTER_RESULT = 'REGISTER_RESULT',
    LOGIN_REQUEST = 'LOGIN_REQUEST',
    LOGIN_RESULT = 'LOGIN_RESULT',
    LOGOUT = 'LOGOUT',
}