export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_RESULT = 'REGISTER_RESULT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESULT = 'LOGIN_RESULT';
export const LOGOUT = 'LOGOUT';

export const GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST';
export const GET_ROOMS_RESULT = 'GET_ROOMS_RESULT';
export const GET_ROOM_REQUEST = 'GET_ROOM_REQUEST';
export const GET_ROOM_RESULT = 'GET_ROOM_RESULT';
export const ADD_ROOM_REQUEST = 'ADD_ROOM_REQUEST';
export const ADD_ROOM_RESULT = 'ADD_ROOM_RESULT';
export const EDIT_ROOM_REQUEST = 'EDIT_ROOM_REQUEST';
export const EDIT_ROOM_RESULT = 'EDIT_ROOM_RESULT';
export const DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST';
export const DELETE_ROOM_RESULT = 'DELETE_ROOM_RESULT';

export const GET_EMPLOYEES_REQUEST = 'GET_EMPLOYEES_REQUEST';
export const GET_EMPLOYEES_RESULT = 'GET_EMPLOYEES_RESULT';
export const GET_EMPLOYEE_REQUEST = 'GET_EMPLOYEE_REQUEST';
export const GET_EMPLOYEE_RESULT = 'GET_EMPLOYEE_RESULT';

export const GET_INVENTORIES_REQUEST = 'GET_INVENTORIES_REQUEST';
export const GET_INVENTORIES_RESULT = 'GET_INVENTORIES_RESULT';
export const GET_INVENTORY_REQUEST = 'GET_INVENTORY_REQUEST';
export const GET_INVENTORY_RESULT = 'GET_INVENTORY_RESULT';